Done.
Setting up the random seed for reproducibility...
Done.
dynamic_import - class_name:  OracleTrainer
Initializing model...
Done.
Initializing datasets...
train_users dict_keys(['dusseldorf6', 'dusseldorf7', 'darmstadt0', 'darmstadt1', 'darmstadt2', 'darmstadt3', 'erfurt4', 'erfurt5', 'erfurt6', 'erfurt7', 'monchengladbach0', 'monchengladbach1', 'krefeld2', 'krefeld3', 'krefeld4', 'krefeld5', 'krefeld6', 'krefeld7', 'monchengladbach2', 'monchengladbach3', 'monchengladbach4', 'monchengladbach5', 'monchengladbach6', 'monchengladbach7', 'tubingen0', 'tubingen1', 'tubingen2', 'tubingen3', 'tubingen4', 'tubingen5', 'bremen0', 'bremen1', 'bremen2', 'bremen3', 'bremen4', 'bremen5', 'cologne6', 'cologne7', 'erfurt0', 'erfurt1', 'erfurt2', 'erfurt3', 'stuttgart4', 'stuttgart5', 'stuttgart6', 'stuttgart7', 'ulm0', 'ulm1', 'jena0', 'jena1', 'jena2', 'jena3', 'jena4', 'jena5', 'bochum4', 'bochum5', 'bochum6', 'bochum7', 'hamburg0', 'hamburg1', 'hamburg2', 'hamburg3', 'hamburg4', 'hamburg5', 'hamburg6', 'hamburg7', 'ulm2', 'ulm3', 'ulm4', 'ulm5', 'ulm6', 'ulm7', 'bremen6', 'bremen7', 'bochum0', 'bochum1', 'bochum2', 'bochum3', 'aachen4', 'aachen5', 'aachen6', 'aachen7', 'krefeld0', 'krefeld1', 'hanover6', 'hanover7', 'weimar0', 'weimar1', 'weimar2', 'weimar3', 'dusseldorf0', 'dusseldorf1', 'dusseldorf2', 'dusseldorf3', 'dusseldorf4', 'dusseldorf5', 'strasbourg2', 'strasbourg3', 'strasbourg4', 'strasbourg5', 'strasbourg6', 'strasbourg7', 'darmstadt4', 'darmstadt5', 'darmstadt6', 'darmstadt7', 'zurich0', 'zurich1', 'weimar4', 'weimar5', 'weimar6', 'weimar7', 'strasbourg0', 'strasbourg1', 'jena6', 'jena7', 'stuttgart0', 'stuttgart1', 'stuttgart2', 'stuttgart3', 'zurich2', 'zurich3', 'zurich4', 'zurich5', 'zurich6', 'zurich7', 'cologne0', 'cologne1', 'cologne2', 'cologne3', 'cologne4', 'cologne5', 'hanover0', 'hanover1', 'hanover2', 'hanover3', 'hanover4', 'hanover5', 'tubingen6', 'tubingen7', 'aachen0', 'aachen1', 'aachen2', 'aachen3']) test_users dict_keys(['test_user'])
Done.
Initializing clients...
dynamic_import - class_name:  OracleClient
Traceback (most recent call last):
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 49, in <module>
    run_experiment()
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 15, in run_experiment
    trainer = trainer_class(args, writer, device, rank, world_size)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 8, in __init__
    super().__init__(args, writer, device, rank, world_size)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/trainer.py", line 11, in __init__
    super().__init__(args, writer, device, rank, world_size)
  File "/home/utente/Scrivania/PROVA/LADD/src/general_trainer.py", line 61, in __init__
    self.__clients_setup()
  File "/home/utente/Scrivania/PROVA/LADD/src/general_trainer.py", line 145, in __clients_setup
    cl = client_class(**cl_args, batch_size=batch_size, test_user=split == 'test')
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/oracle_client.py", line 16, in __init__
    super().__init__(args, client_id, dataset, model, writer, batch_size, world_size, rank, num_gpu,
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/client.py", line 65, in __init__
    self.profiler_path = os.path.join('profiler', self.args.profiler_folder) if self.args.profiler_folder else None
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 49, in <module>
    run_experiment()
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 15, in run_experiment
    trainer = trainer_class(args, writer, device, rank, world_size)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 8, in __init__
    super().__init__(args, writer, device, rank, world_size)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/trainer.py", line 11, in __init__
    super().__init__(args, writer, device, rank, world_size)
  File "/home/utente/Scrivania/PROVA/LADD/src/general_trainer.py", line 61, in __init__
    self.__clients_setup()
  File "/home/utente/Scrivania/PROVA/LADD/src/general_trainer.py", line 145, in __clients_setup
    cl = client_class(**cl_args, batch_size=batch_size, test_user=split == 'test')
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/oracle_client.py", line 16, in __init__
    super().__init__(args, client_id, dataset, model, writer, batch_size, world_size, rank, num_gpu,
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/client.py", line 65, in __init__
    self.profiler_path = os.path.join('profiler', self.args.profiler_folder) if self.args.profiler_folder else None
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/client.py", line 65, in __init__
    self.profiler_path = os.path.join('profiler', self.args.profiler_folder) if self.args.profiler_folder else None
  File "_pydevd_bundle/pydevd_cython.pyx", line 1589, in _pydevd_bundle.pydevd_cython.ThreadTracer.__call__
  File "_pydevd_bundle/pydevd_cython.pyx", line 929, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython.pyx", line 920, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython.pyx", line 317, in _pydevd_bundle.pydevd_cython.PyDBFrame.do_wait_suspend
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1160, in do_wait_suspend
    self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread)
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1175, in _do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 2195, in <module>
    main()
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 2179, in main
    handle_keyboard_interrupt()
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1997, in handle_keyboard_interrupt
    traceback.print_exception(type(value), value, tb, limit=limit)
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/traceback.py", line 105, in print_exception
    print(line, file=file, end="")
KeyboardInterrupt