Done.
Setting up the random seed for reproducibility...
Done.
dynamic_import - class_name:  OracleTrainer
Initializing model...
Done.
Initializing datasets...
Done.
Initializing clients...
dynamic_import - class_name:  OracleClient
Done.
Initializing server...
dynamic_import - class_name:  OracleServer
Running without server optimizer
Running without server optimizer
Done.
Initialize return score, metrics, ckpt, ckpt step...
Setting up metrics...
Done.
Done.
Initializing optimizer and scheduler...
Done.
Generating sample ids for plots...
Done.
dynamic_import - class_name:  OracleClient
The experiment begins...
ROUND 1/2: Training 2 Clients...
CLIENT 1/2: weimar5 RGB
SONO IN get_optimizer_and_scheduler
EPOCH 1: ended.
CLIENT 2/2: hamburg2 RGB
SONO IN get_optimizer_and_scheduler
EPOCH 1: ended.
QUI ARRIVA ALL'UPDATE
Traceback (most recent call last):
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 49, in <module>
    run_experiment()
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 20, in run_experiment
    max_score = trainer.train(*trainer.train_args, **trainer.train_kwargs)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 67, in train
    return self.perform_fed_oracle_training(
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 46, in perform_fed_oracle_training
    self.server.update_model()
KeyboardInterrupt
Exception ignored in: <module 'threading' from '/home/utente/anaconda3/envs/LADD/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/threading.py", line 1435, in _shutdown
    atexit_call()
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/concurrent/futures/process.py", line 90, in _python_exit
    items = list(_threads_wakeups.items())
KeyboardInterrupt: