Done.
Setting up the random seed for reproducibility...
Done.
framework:  federated
fw_task:  oracle
parent_class:  trainer
module_name:  federated
prefix:  Oracle
class_name:  OracleTrainer
Initializing model...
Done.
Initializing datasets...
Done.
Initializing clients...
framework:  federated
fw_task:  oracle
parent_class:  client
module_name:  clients
prefix:  Oracle
class_name:  OracleClient
Done.
Initializing server...
framework:  federated
fw_task:  oracle
parent_class:  server
module_name:  federated
prefix:  Oracle
class_name:  OracleServer
Running without server optimizer
Done.
Initialize return score, metrics, ckpt, ckpt step...
Setting up metrics...
Done.
Done.
Initializing optimizer and scheduler...
Done.
Generating sample ids for plots...
Done.
framework:  federated
fw_task:  oracle
parent_class:  client
module_name:  clients
prefix:  Oracle
class_name:  OracleClient
The experiment begins...
Lunghezza max_scores 1
ROUND 1/15: Training 15 Clients...
CLIENT 1/15: RGB
EPOCH 1: ended.
CLIENT 2/15: RGB
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 152, in exc_handler
    traceback.print_exception(exc_type, exc, tb)
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/traceback.py", line 103, in print_exception
    for line in TracebackException(
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/traceback.py", line 517, in __init__
    self.stack = StackSummary.extract(
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/traceback.py", line 353, in extract
    linecache.lazycache(filename, f.f_globals)
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/linecache.py", line 169, in lazycache
    name = module_globals.get('__name__')
KeyboardInterrupt
Original exception was:
Traceback (most recent call last):
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 47, in <module>
    run_experiment()
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 18, in run_experiment
    max_score = trainer.train(*trainer.train_args, **trainer.train_kwargs)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 59, in train
    return self.perform_fed_oracle_training(
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 37, in perform_fed_oracle_training
    losses = self.server.train_clients(partial_metric=partial_train_metric)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/servers/oracle_server.py", line 35, in train_clients
    out = c.train(partial_metric, r=r)
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/oracle_client.py", line 194, in train
    dict_all_iters_losses = self.run_epoch(epoch, optimizer, metric=partial_metric, r=r)
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/oracle_client.py", line 166, in run_epoch
    self.__exec_epoch(optimizer, cur_epoch, metric, scheduler, plot_lr, dict_all_iters_losses,
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/oracle_client.py", line 91, in __exec_epoch
    for cur_step, samples in enumerate(self.loader):
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1142, in _get_data
    success, data = self._try_get_data()
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt